apps/quiniela/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'quiniela'
urlpatterns = [
    # Quiniela related views
    re_path('^$', views.quiniela_index, name='user_quinielas'),
    path('<int:quiniela_id>/', views.quiniela_details, name='quiniela_details'),
    path('<int:quiniela_id>/join/', views.quiniela_join, name='quiniela_join'),
    path('<int:quiniela_id>/delete/', views.quiniela_delete, name='quiniela_delete'),
    path('<int:quiniela_id>/@<str:username>/', views.quiniela_from_user, name='quiniela_from_user'),
    # Oscarcoin
    path('oscarcoin/', views.oscarcoin_update, name='oscarcoin_uptade'),
]

settings/urls.py
"""softwareII URL Configuration"""

from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

app_name = 'urls'
urlpatterns = [
    # Admin Urls
    re_path('^admin/', admin.site.urls),
    # User Urls
    re_path('^user/', include('apps.users.urls', namespace='users')),
    # Chat Urls
    #re_path('^chat/', include('apps.chat.urls', namespace='chat')),
    # Quiniela Urls
    re_path('^user/quinielas/', include('apps.quiniela.urls', namespace='quiniela')),
    # Api Urls
    #re_path('^api/', include('apps.api.urls', namespace='api')),
    # Oauth2 Urls
    #re_path('^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    # Main Urls
    re_path('^', include('apps.main.urls')),


    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib.auth.views import logout, login

from . import views

urlpatterns = [
    # User registration and authentication views
    url(r'^login/$', login, kwargs={'redirect_authenticated_user': True}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^sign_up/$', views.sign_up, name='user_sign_up'),

    # User related views
    url(r'^$', views.user_index, name='user_index'),

    # Social related views
    url(r'^profiles/@(?P<username>\w+)$', views.user_profile, name='user_profile'),

    # Include user member-its urls
    url(r'^', include('memberits.urls', namespace='member-it')),
]

templates/partials/nav.html
{% load static %}
{% load quiniela_tournamenttags %}


  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
  {% if not user.is_authenticated %}
  <ul class="nav navbar-nav">
    <li>
      <a href="{% url 'quiniela:user_quinielas' %}" class="pages-header">
        <b>Quinielas</b>
      </a>
    </li>
  </ul>

  <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu no-user">
      <ul class="nav navbar-nav">

        <!-- Login and Sign in icons-->
        <li>
          <a href="{% url 'users:login' %}?next=/user/" class="login-header">
            <b>Login</b>
            <i class="fa fa-user-circle"></i>
          </a>
        </li>
        <li>
          <!-- Menu toggle button -->
          <a href="{% url 'users:user_sign_up' %}" class="sign-up-header">
            <b>Sign Up</b>
            <i class="fa fa-check-square-o"></i>
          </a>
        </li>
      </ul>
  {% else %}
    {% block header %}
    <ul class="nav navbar-nav">
      <li>
        <a href="{% url 'quiniela:user_quinielas' %}" class="pages-header">
          <b>Quinielas</b>
        </a>
      </li>
      <li class="hidden-md hidden-lg">
        <a href="#">Oscarcoin: {% get_oscarcoin %},00bsfS</a>
      </li>
    </ul>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

      <li class="visible-md visible-lg">
        <a href="#">Oscarcoin: {% get_oscarcoin %},00bsfS</a>
      </li>

        <!-- Messages: style can be found in dropdown.less-->
        <li class="dropdown messages-menu">
          <!-- Menu toggle button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">0</span>
          </a>
          <ul class="dropdown-menu">

            <li class="header">You have 0 messages</li>
            <li>
              <!-- inner menu: contains the messages -->
              <ul class="menu">
                <li><!-- start message -->
                  <a href="#">
                    <div class="pull-left">
                      <!-- User Image -->
                      {% if user.profile.image %}
                        <img src="{{ user.profile.image.url }}" class="img-circle" alt="User Image">
                      {% else %}
                        <img src="{% static 'dist/img/generic-user-avatar.png' %}" class="img-circle" alt="User Image">
                      {% endif %}
                    </div>
                    <!-- Message title and timestamp -->
                    <h4>
                      Support Team
                      <small><i class="fa fa-clock-o"></i> 5 mins</small>
                    </h4>
                    <!-- The message -->
                    <p>Why not buy a new awesome theme?</p>
                  </a>
                </li>
                <!-- end message -->
              </ul>
              <!-- /.menu -->
            </li>
            <li class="footer"><a href="#">See All Messages</a></li>
          </ul>
        </li>
        <!-- /.messages-menu -->

        <!-- Notifications Menu -->
        <li class="dropdown notifications-menu">
          <!-- Menu toggle button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">0</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 0 notifications</li>
            <li>
              <!-- Inner Menu: contains the notifications -->
              <ul class="menu">
                {% for request in user.profile.get_pending_requests %}
                <li class="user_request_confirm" data-user="{{ request.from_user.user.username }}"
                  data-reason="{{ request.reason }}"><!-- start notification -->
                  <i class="fa fa-users text-aqua"></i>
                  {% include 'user_request.html' %}
                </li>
                {% endfor %}
                <!-- end notification -->
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>
        <!-- Tasks Menu -->
        <li class="dropdown tasks-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">0</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 0 memberIts!</li>
            <li>
              <!-- Inner menu: contains the tasks -->
              <ul class="menu">
                <li><!-- Task item -->
                  <a href="#">
                    <!-- Task title and progress text -->
                    <h3>
                      Design some buttons
                      <small class="pull-right">20%</small>
                    </h3>
                    <!-- The progress bar -->
                    <div class="progress xs">
                      <!-- Change the css width attribute to simulate progress -->
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                           aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
              </ul>
            </li>
            <li class="footer">
              <a href="#">View all memberIts</a>
            </li>
          </ul>
        </li>
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            {% if user.profile.image %}
              <img src="{{ user.profile.image.url }}" class="user-image" alt="User Image">
            {% else %}
              <img src="{% static 'dist/img/generic-user-avatar.png' %}" class="user-image" alt="User Image">
            {% endif %}
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span>{{ user.username }}</span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              {% if user.profile.image %}
                <img src="{{ user.profile.image.url }}" class="img-circle" alt="User Image">
              {% else %}
                <img src="{% static 'dist/img/generic-user-avatar.png' %}" class="img-circle" alt="User Image">
              {% endif %}
              <p>
                {{ user.username }}
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="row">
                <div class="col-xs-4 text-center">
                  <a href="#">Followers</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Sales</a>
                </div>
                <div class="col-xs-4 text-center">
                  <a href="#">Friends</a>
                </div>
              </div>
              <!-- /.row -->
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="{% url 'users:logout' %}?next=/" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>


        <!-- Control Sidebar Toggle Button -->
        <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li>
      </ul>
    </div>
    {% endblock %}
  {% endif %}

  </nav>
  