apps/main/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

apps/quiniela/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'quiniela'
urlpatterns = [
    # Quiniela related views
    re_path('^$', views.quiniela_index, name='user_quinielas'),
    path('<int:quiniela_id>/', views.quiniela_details, name='quiniela_details'),
    path('<int:quiniela_id>/join/', views.quiniela_join, name='quiniela_join'),
    path('<int:quiniela_id>/delete/', views.quiniela_delete, name='quiniela_delete'),
    path('<int:quiniela_id>/@<str:username>/', views.quiniela_from_user, name='quiniela_from_user'),
    # Oscarcoin
    path('oscarcoin/', views.oscarcoin_update, name='oscarcoin_uptade'),
]

settings/urls.py
"""softwareII URL Configuration"""

from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

app_name = 'urls'
urlpatterns = [
    # Admin Urls
    re_path('^admin/', admin.site.urls),
    # User Urls
    re_path('^user/', include('apps.users.urls', namespace='users')),
    # Chat Urls
    #re_path('^chat/', include('apps.chat.urls', namespace='chat')),
    # Quiniela Urls
    re_path('^user/quinielas/', include('apps.quiniela.urls', namespace='quiniela')),
    # Api Urls
    #re_path('^api/', include('apps.api.urls', namespace='api')),
    # Oauth2 Urls
    #re_path('^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    # Main Urls
    re_path('^', include('apps.main.urls')),


    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib.auth.views import logout, login

from . import views

urlpatterns = [
    # User registration and authentication views
    url(r'^login/$', login, kwargs={'redirect_authenticated_user': True}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^sign_up/$', views.sign_up, name='user_sign_up'),

    # User related views
    url(r'^$', views.user_index, name='user_index'),

    # Social related views
    url(r'^profiles/@(?P<username>\w+)$', views.user_profile, name='user_profile'),

    # Include user member-its urls
    url(r'^', include('memberits.urls', namespace='member-it')),
]

apps/quiniela/forms.py
from django import forms
from django.utils.translation import ugettext, ugettext_lazy as _

from .models import Quiniela, Game, GameResult, OscarCoin


class QuinielaForm(forms.ModelForm):

    class Meta:
        model = Quiniela
        exclude = ('members', 'admin', 'tags')


class GameResultForm(forms.ModelForm):

    class Meta:
        model = GameResult
        exclude = ('game', 'user')


class BlockedGameResultForm(forms.ModelForm):

    class Meta:
        model = GameResult
        exclude = ('game', 'user')
        readonly_fields = ('score_home', 'score_away')

    def __init__(self, *args, **kwargs):
        super(BlockedGameResultForm, self).__init__(*args, **kwargs)
        self.fields['score_home'].widget.attrs['readonly'] = True
        self.fields['score_away'].widget.attrs['readonly'] = True

    def get_winner(self):
        return self.instance.get_winner()


class InviteUsersForm(forms.Form):
    users = forms.CharField(max_length=50)


class OscarCoinForm(forms.ModelForm):

    error_messages = {
        'password_mismatch': _("The Secret Phrase is not correct."),
    }
    secret_phrase = forms.CharField(label=_("Secret Phrase"), widget=forms.PasswordInput)

    class Meta:
        model = OscarCoin
        fields = ['value', 'secret_phrase']

    def clean_secret_phrase(self):
        phrase = self.cleaned_data.get("secret_phrase")
        if phrase and phrase != "merwebochico":
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return phrase

apps/quiniela/views.py
import datetime

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory, formset_factory

from .models import Quiniela, MemberFixture, GameResult, Group, MemberFixture, OscarCoin
from .forms import QuinielaForm, GameResultForm, BlockedGameResultForm, InviteUsersForm, Game, OscarCoinForm
from apps.users.models import Profile


# User quiniela's view
@login_required
def quiniela_index(request):
    if request.method == 'POST':
        form = QuinielaForm(request.POST)
        if form.is_valid():
            quiniela = form.save(commit=False)
            quiniela.admin = request.user.profile
            quiniela.save()
            quiniela.members.add(request.user.profile)
    else:
        form = QuinielaForm()

    return render(
        request,
        'quiniela_index.html',
        context={
            'quinielas': Quiniela.objects.filter(members=request.user.profile),
            'public_quinielas': Quiniela.objects.filter(public=True),
            'form': form,
        }
    )

# View to process all quiniela details
@login_required
def quiniela_details(request, quiniela_id):
    is_member = True
    inviting = False
    active = 0
    phase = 3
    phases_limit = 16
    quiniela = get_object_or_404(Quiniela, id=quiniela_id)
    quiniela_games = quiniela.tournament.fixture.all().order_by('match_datetime')
    phases_prefixes = ['group1', 'group2', 'group3', 'group4', 'group5', 'group6', 'group7', 'group8']
    initial_data = []
    groups_formsets = []
    formsets = []
    invite_errors = []
    invite_notifications = []
    invite_fs = formset_factory(InviteUsersForm)
    results_formset = modelformset_factory(GameResult, form=GameResultForm, extra=0)
    blocked_results_formset = modelformset_factory(GameResult, form=BlockedGameResultForm, extra=0)
    groups = Group.objects.filter(tournament=quiniela.tournament).order_by('name')

    (active, phase) = prepare_phases(active, phase, quiniela_games, groups)

    # To active leaderboards tab
    if request.GET.get('leaderboard') == 'True':
        active = 0

    # To maintain url vars
    if request.GET.get('joined') == 'True':
        invite_notifications.append('You have joined this Quiniela =)!')
        inviting = True

    # If user is member of this Quiniela
    if request.user.profile in quiniela.members.all():
        # Update current predictions from user
        if request.method == 'POST':
            # To Clear url vars
            if request.GET.get('joined') == 'True':
                inviting = False
                invite_notifications = []

            # Check if user has added other users
            invite_formset = invite_fs(request.POST or None, prefix='invite_users')
            if invite_formset.is_valid():
                for form in invite_formset:
                    if form.is_valid():
                        if form.cleaned_data.get('users'):
                            active = 0
                            inviting = True
                            for user in form.cleaned_data.get('users').replace(' ','').split(';'):
                                useraux = Profile.objects.filter(user__username=user) or Profile.objects.filter(user__email=user)
                                if useraux and useraux[0] not in quiniela.members.all():
                                    quiniela.members.add(useraux[0])
                                    invite_notifications.append('User ' + user + ' has been added to this Quiniela!')
                                elif useraux:
                                    invite_errors.append('User ' + user + ' is already in this Quiniela.')
                                else:
                                    invite_errors.append('User ' + user + ' does not exists.')
            else:
                print(invite_formset.errors)

            for prefix in phases_prefixes[active-1:]:
                formsets.append(results_formset(request.POST or None, prefix=prefix))

            for formset in formsets:
                if formset and formset.is_valid():
                    for form in formset:
                        if form.is_valid():
                            if(form.instance.game.match_datetime >= datetime.datetime.now(form.instance.game.match_datetime.tzinfo)):
                                form.save()
                        else:
                            print(form.errors)
                else:
                    print(formset.errors)
            formsets = []

        # Check if user already have a prediction for this quiniela
        prediction = MemberFixture.objects.filter(
            user=request.user.profile,
            tournament=quiniela.tournament,
            quiniela=quiniela
        )

        # Create predictions for each game in case the user is new to the quiniela
        # or the game is recently added to that quiniela
        if not prediction:
            prediction = MemberFixture(
                user=request.user.profile,
                tournament=quiniela.tournament,
                quiniela=quiniela,
            )
            prediction.save()
        else:
            prediction = prediction[0]

        # MemberFixture from user ordered by date
        qset = prediction.results.order_by('game__match_datetime')
        init = 0
        lim = 0 # To save the last phase
        end = phases_limit
        # Initialize passed games results with blocked gameforms
        for game in quiniela_games:
            aux = qset.filter(game=game)
            if game.match_datetime <= datetime.datetime.now(game.match_datetime.tzinfo):
                init += 1
                # Phase limit border cases
                if init == end:
                    formsets.append(blocked_results_formset(queryset=qset[end-phases_limit:init]))
                    lim += 1
                    (init, end, phases_limit) = phasesLimit(init, end, phases_limit)
                    if init < 0:
                        break

            # If that game prediction does not exist, create it
            if not aux:
                gr = GameResult(
                    game=game,
                    user=request.user.profile,
                )
                gr.save()
                prediction.results.add(gr)

        # If the number of blocked results isn't round with a group number limit
        if init != end and init > 0:
            if (end - phases_limit) != init:
                formsets.append(blocked_results_formset(queryset=qset[end-phases_limit:init]))

        # Create and populate new formsets with the prediction data starting from the last BlockedGameResult
        for prefix in phases_prefixes[lim:]:
            formsets.append(results_formset(queryset=qset[init:end], prefix=prefix))
            (init, end, phases_limit) = phasesLimit(init, end, phases_limit)

            if init < 0:
                break

        # Populate template context vars
        phases_limit = 16
        end = phases_limit
        count = 0
        prefix = 0
        for formset in formsets:
            if count % phases_limit == 0:
                group_forms = []

            for form in formset:
                group_forms.append((quiniela_games[count], form))
                count += 1

            if count % phases_limit == 0:
                groups_formsets.append((group_forms, formset.management_form, phases_prefixes[prefix]))
                prefix += 1
                (count, end, phases_limit) = phasesLimit(count, end, phases_limit)

                if count < 0:
                    break

    # If request.user is not in this quinielas members
    else:
        is_member = False
        init = 0
        end = phases_limit
        count = 0
        prefix = 0
        for game in quiniela_games:
            if count % phases_limit == 0:
                group_forms = []

            group_forms.append((game, None))
            count += 1
            if count % phases_limit == 0:
                groups_formsets.append((group_forms, None, phases_prefixes[prefix]))
                prefix += 1
                (init, end, phases_limit) = phasesLimit(count, end, phases_limit)
                if init < 0:
                    break

        if count % phases_limit != 0:
            groups_formsets.append((group_forms, None, phases_prefixes[prefix]))
            
    # Request and request.user independant code and initializations
    invite_formset = invite_fs(prefix='invite_users')
    leaders = MemberFixture.objects.filter(
                tournament=quiniela.tournament,
                quiniela=quiniela
            ).order_by('-score')

    pendings = []
    for user in quiniela.members.all():
        if not leaders.filter(user=user):
            pendings.append(user)

    return render(
        request,
        'quiniela_details.html',
        context={
            'is_member': is_member,
            'quiniela': quiniela,
            'active': active,
            'phase': phase,
            'inviting': inviting,
            'group_predictions': groups_formsets,
            'leaders': leaders,
            'pendings': pendings,
            'groups': groups,
            'invite_formset': invite_formset,
            'invite_errors': invite_errors,
            'invite_notifications': invite_notifications,
        }
    )


# View to delete a quiniela
@login_required
def quiniela_join(request, quiniela_id):
    quiniela = get_object_or_404(Quiniela, id=quiniela_id)
    quiniela.members.add(request.user.profile)
    response = HttpResponse()
    response = redirect('quiniela:quiniela_details', quiniela_id=quiniela_id)
    response['Location'] += '?leaderboard=True&joined=True'
    return response


# View to delete a quiniela
@login_required
def quiniela_delete(request, quiniela_id):
    quiniela = get_object_or_404(Quiniela, id=quiniela_id)

apps/quiniela/templates/oscarcoin_update.html
{% extends "base_main.html" %}

{% block content %}
    {# Load the tag library #}
    {% load bootstrap3 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    <div class="col-sm-6">
        <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
            {% buttons %}
           <button type="submit">Update Oscarcoin</button>
           {% endbuttons %}
        </form>
    </div>
{% endblock %}

apps/quiniela/templates/quiniela_index.html
{% extends "base_main.html" %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content-header %}
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
        <li><a href="{% url 'main:home' %}">Home</a></li>
        <li class="active">Quinielas</li>
    </ol>
    Hi {{ user.username }}!
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-6">
        {% if quinielas %}
            <h3> Quinielas en las que estas participando</h3>
            {% for quiniela in quinielas %}
            <div class="row">
                <div class="col-xs-12 quiniela">
                    <div class="box">
                        <h5><a href="{% url 'quiniela:quiniela_details' quiniela.id %}">
                            {% if quiniela.tournament.image %}
                                <img src="{{quiniela.tournament.image.url}}" width="55px" height="55px">
                            {% endif %}
                            {{ quiniela.tournament.name }}
                             - 
                             {% if quiniela.image %}
                                <img src="{{quiniela.image.url}}" width="55px" height="55px">
                            {% endif %}
                            {{ quiniela.name }}
                        </a></h5>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
        <h3>No estas participando en ninguna quiniela =(</h3>
        <hr>
        {% endif %}
        </div>
        <div class="col-lg-6">
        {% if public_quinielas %}
            <h3> Quinielas Publicas</h3>
            {% for quiniela in public_quinielas %}
            <div class="row">
                <div class="col-xs-12 quiniela">
                    <div class="box">
                        <h5><a href="{% url 'quiniela:quiniela_details' quiniela.id %}">
                            {% if quiniela.image %}
                                <img src="{{quiniela.image.url}}" width="55px" height="55px">
                            {% endif %}
                            {{ quiniela.name }} -
                            {% if quiniela.tournament.image %}
                                <img src="{{quiniela.tournament.image.url}}" width="55px" height="55px">
                            {% endif %}
                            {{ quiniela.tournament.name }}
                        </a></h5>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% endif %}
        </div>
    </div>
    <hr>
    
    <h4>Crear Quiniela:</h4>
    {% bootstrap_messages %}
    <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit">Crear Nueva Quiniela</button>
    {% endbuttons %}
    </form>
{% endblock %}

{% block jsblock %}
{% endblock %}